enhancement:
  - src/**

workflow:
  - .github/**

documentation:
  - CHANGELOG.md
  - README.md
  - CONTRIBUTORS.md

dependencies:
  - pom.xml

automerge:
  - all: [ 'README.md' ]
  - all: [ 'CHANGELOG.md' ]
  - all: [ 'CONTRIBUTORS.md' ]