enhancement:
  - changed-files:
      - any-glob-to-any-file: src/**

workflow:
  - changed-files:
      - any-glob-to-any-file: .github/**

dependencies:
  - changed-files:
      - any-glob-to-any-file: pom.xml

documentation:
  - changed-files:
      - any-glob-to-any-file: [ ' CHANGELOG.md' ,'README.md' ,'CONTRIBUTORS.md' ,'LICENSE' ,'SECURITY.md' ]

ci:
  - changed-files:
      - any-glob-to-any-file: [ '.mvn/**' ,'.imgbotconfig' ,'.mergify.yml' ,'qodana.yaml' ]
