name: Maven Central Repo Deployment
# 触发脚本的事件  这里为发布release之后触发
on:
  workflow_dispatch:
  release:
    types: [ released ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with: # running setup-java again overwrites the settings.xml
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'

      - name: Release Maven package
        uses: WasiqB/maven-publish-action@v2.9.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSWORD }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_TOKEN }}
          server_id: 'sonatype-nexus-snapshots'
          maven_profiles: 'release'
